#!/bin/sh

echo "foamClearPolyMesh"
foamClearPolyMesh

./Clean
cp -r 0org 0

echo "blockMesh"
blockMesh > log.blockMesh


#echo "createPatch"
#createPatch -overwrite > log.CreatePatch
#
#echo "refineMesh"
#refineMesh -dict system/refineMeshDict -overwrite > log.refineMesh


echo "snappyHexMesh"
snappyHexMesh -overwrite > log.snappy


echo "setSet0"
setSet -constant > log.setSet0 << EOF

faceSet inlet new boxToFace (1.099 -0.001 0.099) (2.901 0.001 1.901)
faceSet inglass1 new boxToFace (0.199 -0.001 0.099) (1.101 0.001 1.901)
faceSet inglass2 new boxToFace (2.899 -0.001 0.099) (3.801 0.001 1.901)

faceSet midglass new boxToFace (3.999 2.999 0.899) (4.001 5.001 2.201)

faceSet outlet new boxToFace (1.199 7.999 1.199) (2.001 8.001 1.801)
faceSet outglass new boxToFace (1.999 7.999 1.199) (2.801 8.001 1.801)

quit
EOF


echo "createPatch"
createPatch -overwrite > log.createPatch

#echo "refineMesh0"
#refineMesh -dict system/refineMeshDict -overwrite > log.refineMesh1

echo "renumberMesh"
renumberMesh -overwrite > log.renumber

echo "checkMesh"
checkMesh > log.checkMesh

echo "That's all for creating mesh"


#echo "radiation"
#./Radiation
