#!/bin/sh

echo "setZone"
setSet -constant > log.setSet_zone <<EOF

cellSet back_left_T new boxToCell (1.779 3.499 1.039) (2.001 3.641 1.461)
cellZoneSet back_left_T new setToCellZone back_left_T

cellSet back_right_T new boxToCell (1.599 3.499 1.039) (1.821 3.641 1.461)
cellZoneSet back_right_T new setToCellZone back_right_T

cellSet chest_left_T new boxToCell (1.759 3.359 1.019) (2.001 3.601 1.461)
cellZoneSet chest_left_T new setToCellZone chest_left_T

cellSet chest_right_T new boxToCell (1.599 3.359 1.019) (1.821 3.601 1.461)
cellZoneSet chest_right_T new setToCellZone chest_right_T

cellSet waist_left_back_T new boxToCell (1.779 3.499 0.759) (1.961 3.681 1.121)
cellZoneSet waist_left_back_T new setToCellZone waist_left_back_T

cellSet waist_left_front_T new boxToCell (1.779 3.399 0.759) (1.961 3.581 1.121)
cellZoneSet waist_left_front_T new setToCellZone waist_left_front_T

cellSet waist_right_back_T new boxToCell (1.639 3.499 0.759) (1.809 3.681 1.121)
cellZoneSet waist_right_back_T new setToCellZone waist_right_back_T

cellSet waist_right_front_T new boxToCell (1.639 3.399 0.759) (1.809 3.581 1.121)
cellZoneSet waist_right_front_T new setToCellZone waist_right_front_T

cellSet femur_left_back_T new boxToCell (1.779 3.519 0.499) (2.001 3.661 1.021)
cellZoneSet femur_left_back_T new setToCellZone femur_left_back_T

cellSet femur_left_front_T new boxToCell (1.779 3.439 0.499) (2.001 3.581 1.0211)
cellZoneSet femur_left_front_T new setToCellZone femur_left_front_T

cellSet femur_right_back_T new boxToCell (1.599 3.519 0.499) (1.801 3.661 1.021)
cellZoneSet femur_right_back_T new setToCellZone femur_right_back_T

cellSet femur_right_front_T new boxToCell (1.599 3.439 0.499) (1.801 3.581 1.021)
cellZoneSet femur_right_front_T new setToCellZone femur_right_front_T

cellSet lowerleg_left_back_T new boxToCell (1.699 3.539 0.029) (1.901 3.621 0.599)
cellZoneSet lowerleg_left_back_T new setToCellZone lowerleg_left_back_T

cellSet lowerleg_left_front_T new boxToCell (1.839 3.479 0.029) (1.901 3.601 0.599)
cellZoneSet lowerleg_left_front_T new setToCellZone lowerleg_left_front_T

cellSet lowerleg_right_back_T new boxToCell (1.629 3.539 0.029) (1.759 3.621 0.599)
cellZoneSet lowerleg_right_back_T new setToCellZone lowerleg_right_back_T

cellSet lowerleg_right_front_T new boxToCell (1.629 3.479 0.029) (1.759 3.659 0.599)
cellZoneSet lowerleg_right_front_T new setToCellZone lowerleg_right_front_T

cellSet upperarm_left_back_T new boxToCell (1.919 3.519 1.399) (2.081 3.661 1.701)
cellZoneSet upperarm_left_back_T new setToCellZone upperarm_left_back_T

cellSet upperarm_left_front_T new boxToCell (1.919 3.399 1.399) (2.081 3.601 1.701)
cellZoneSet upperarm_left_front_T new setToCellZone upperarm_left_front_T

cellSet upperarm_right_back_T new boxToCell (1.699 3.519 1.399) (1.901 3.661 1.701)
cellZoneSet upperarm_right_back_T new setToCellZone upperarm_right_back_T

cellSet upperarm_right_front_T new boxToCell (1.519 3.499 1.059) (1.681 3.601 1.441)
cellZoneSet upperarm_right_front_T new setToCellZone upperarm_right_front_T

cellSet forearm_left_back_T new boxToCell (1.999 3.519 0.839) (2.081 3.801 1.131)
cellZoneSet forearm_left_back_T new setToCellZone forearm_left_back_T

cellSet forearm_left_front_T new boxToCell (1.999 3.519 0.839) (2.081 3.601 1.131)
cellZoneSet forearm_left_front_T new setToCellZone forearm_left_front_T

cellSet forearm_right_back_T new boxToCell (1.519 3.519 0.819) (1.601 3.661 1.131)
cellZoneSet forearm_right_back_T new setToCellZone forearm_right_back_T

cellSet forearm_right_front_T new boxToCell (1.519 3.499 0.819) (1.601 3.641 1.131)
cellZoneSet forearm_right_front_T new setToCellZone forearm_right_front_T

cellSet foot_left_T new boxToCell (1.859 3.359 -0.001) (1.961 3.621 0.121)
cellZoneSet foot_left_T new setToCellZone foot_left_T

cellSet foot_right_T new boxToCell (1.639 3.359 -0.001) (1.721 3.621 0.121)
cellZoneSet foot_right_T new setToCellZone foot_right_T

cellSet hand_left_T new boxToCell (1.999 3.479 0.639) (2.061 3.601 0.901)
cellZoneSet hand_left_T new setToCellZone hand_left_T

cellSet hand_right_T new boxToCell (1.539 3.479 0.639) (1.601 3.601 0.901)
cellZoneSet hand_right_T new setToCellZone hand_right_T

cellSet neck_back_T new boxToCell (1.739 3.499 1.399) (1.901 3.601 1.501)
cellZoneSet neck_back_T new setToCellZone neck_back_T

cellSet neck_front_T new boxToCell (1.739 3.459 1.399) (1.861 3.541 1.501)
cellZoneSet neck_front_T new setToCellZone neck_front_T

cellSet face_T new boxToCell (1.699 3.399 1.419) (1.901 3.501 1.661)
cellZoneSet face_T new setToCellZone face_T

cellSet head_T new boxToCell (1.699 3.399 1.419) (1.901 3.601 1.661)
cellZoneSet head_T new setToCellZone head_T

cellSet w_internal_T new boxToCell (-0.001 1.619 -2.001) (4.001 4.021 1.801)
cellZoneSet w_internal_T new setToCellZone w_internal_T


quit
EOF
